apiVersion: apps/v1
kind: Deployment
metadata:
  name: boat-house-calculator
  namespace: #{K8S_NAMESPACE}#
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boat-house-calculator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: boat-house-calculator
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: boat-house-calculator
        image: #{REGISTRY_URL}#/#{REGISTRY_NS}#/boat-house-calculator:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: boat-house-calculator
  namespace: #{K8S_NAMESPACE}#
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: boat-house-calculator